<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

name:    <%= env :name,    'Pi' %>
twitter: <%= env :twitter, 'kohwi' %>
github:  <%= env :github,  'soundcloud/insights'  %>
email:   <%= env :email,   'insight@soundcloud.com'  %>
about:   <%= env :about,   'Home of the Insight Team' %>

# Google Analytics
ga_id:   <%= env :ga,      ''  %>
